FROM php:8.3-cli-alpine

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
COPY ./conf/php/cli.sh /tmp/cli.sh
COPY ./conf/octane/start.sh /opt/start.sh
COPY ./conf/shell/runtime.sh /opt/runtime.sh
COPY ./conf/octane/nginx.conf /run/nginx/nginx.conf
COPY ./conf/octane/octane.ini /etc/supervisor.d/octane.ini

ARG DOCKER_ENV=production
ENV TIMEZONE="Asia/Shanghai" \
    LANG=C.UTF-8 \
    COMPOSER_ALLOW_SUPERUSER=1 \
    OPCACHE_ENABLE=1 \
    OCTANE_WORKERS=4 \
    OCTANE_TASKS=4 \
    OCTANE_MAX_REQUESTS=2000 \
    OCTANE_START=true

WORKDIR /var/www/html

RUN set -eux; \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories; \
    cat /etc/apk/repositories; \
    apk update; \
    apk add --no-cache tzdata bash bash-completion supervisor nginx; \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime; \
    echo "Asia/Shanghai" > /etc/timezone; \
    apk del tzdata

RUN set -eux; \
    install-php-extensions \
        intl \
        ldap \
        dba \
        shmop \
        calendar \
        exif \
        gettext \
        pcntl \
        sysvsem \
        sysvshm \
        sysvmsg \
        soap \
        pdo_mysql \
        mysqli \
        bcmath \
        sockets \
        zip \
        bz2

RUN set -eux; \
    install-php-extensions \
        amqp \
        mongodb \
        xlswriter \
        igbinary \
        lzf \
        lz4

RUN set -eux; \
    install-php-extensions \
        redis \
        opcache \
        @composer

RUN set -eux; \
    composer config -g repo.packagist composer https://mirrors.cloud.tencent.com/composer/

RUN set -eux; \
    chmod +x /tmp/php-fpm.sh; \
    /bin/bash -x /tmp/php-fpm.sh

RUN set -eux; \
    chmod +x /opt/start.sh; \
    mkdir -p /run/nginx; \
    rm -rf /var/cache/apk/* /tmp/* /usr/share/man /var/lib/apt/lists/*

EXPOSE 80 8000

CMD ["/opt/start.sh"]
