name: Docker Image CI

on:
  push:
    branches: [ "v2" ]
  pull_request:
    branches: [ "v2" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build The Docker Image
      run: docker build -f Dockerfile-8.2-octane -t sync402/docker-php:octane-8.2.4 . \
    - name: Push The Docker Image
      run : docker push sync402/docker-php:octane-8.2.4
