name: Docker Image Octane

on:
  push:
    branches: [ "v2" ]
  pull_request:
    branches: [ "v2" ]

env:
  REGISTRY: ''
  IMAGE_NAME: 'sync402/docker-php'
jobs:

  build:
    strategy:
      matrix:
        version: ["7.1","7.2","7.3","7.4","8.0","8.1","8.2"]
        edition: ["web","octane"]
        registrg: ["registry.cn-shanghai.aliyuncs.com","registry.cn-hangzhou.aliyuncs.com"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build The Docker Image
      run: docker build . --file Dockerfile-${{matrix.version}}-${{matrix.edition}} --tag ${{matrix.registrg}}:${{matrix.edition}}-${{matrix.version}}

    # 登录  
    - name: Log into registry ${{ matrix.registrg }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
          registry: ${{ matrix.registrg }}
          username: 'ap3747a7y@aliyun.com'
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
          images:  ${{ matrix.registrg }}:${{ matrix.edition }}-${{ matrix.version }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # tag event
            type=ref,enable=true,priority=600,prefix=,suffix=,event=tag

    - name: Build And push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
