name: Docker Image Octane

on:
  push:
    branches: [ "v2" ]
  pull_request:
    branches: [ "v2" ]

env:
  REGISTRY: ''
  IMAGE_NAME: 'sync402/docker-php:octane'
jobs:

  build:
    strategy:
      matrix:
        version: [7.1,7.2,7.3,7.4,"8.0",8.1,8.2]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build The Docker Image
      run: docker build . --file Dockerfile-${{matrix.version}}-octane --tag ${{env.IMAGE_NAME}}-${{matrix.version}}

    # 登录  
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
          images: ${{ env.IMAGE_NAME }}-${{ matrix.version }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # tag event
            type=ref,enable=true,priority=600,prefix=,suffix=,event=tag

    - name: Build And push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
